USE codeup_test_db;
DROP TABLE IF EXISTS albums;
CREATE TABLE albums (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    artist VARCHAR(250) NOT NULL,
    name VARCHAR(250) NOT NULL,
    release_date SMALLINT UNSIGNED,
    sales FLOAT NOT NULL DEFAULT 0,
    genre VARCHAR(250) NOT NULL,
    PRIMARY KEY (id)
);